"""Update Translationunits.translations

Revision ID: 1f3ac20943eb
Revises: 9c2ea80c148d
Create Date: 2020-07-23 13:24:01.371407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1f3ac20943eb"
down_revision = "9c2ea80c148d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "translationunits", "default", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "translationunits", "translation", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "translationunits", "translation", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "translationunits", "default", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###
