"""Update Translationunits.label

Revision ID: 96cefb27169f
Revises: 1f3ac20943eb
Create Date: 2020-07-23 21:22:28.340392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "96cefb27169f"
down_revision = "1f3ac20943eb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("translationunits", sa.Column("label", sa.String(), nullable=False))
    op.alter_column(
        "translationunits", "default", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "translationunits", "default", existing_type=sa.VARCHAR(), nullable=True
    )
    op.drop_column("translationunits", "label")
    # ### end Alembic commands ###
