"""Add Translationunits.default

Revision ID: 9c2ea80c148d
Revises: c43b9106a3ab
Create Date: 2020-07-23 12:57:32.415073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c2ea80c148d'
down_revision = 'c43b9106a3ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translationunits', sa.Column('default', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('translationunits', 'default')
    # ### end Alembic commands ###
